baseurl = "https://ghuo.me"
languageCode = "zh-cn"
DefaultContentLanguage = "zh-cn"
title = "Guan Huo's Notes"

[markup]
  [markup.highlight]
    lineNos = false
    lineNumbersInTable = false
    noClasses = false

[params]
  description = "*KEEP IT SIMPLE, STUPID.*"
  author = "Guan Huo"

[taxonomies]
  tag = "tags"
  series = "series"

[languages]
  [languages.zh-cn]
    weight = 2
